Repository nuodb/nuodb-insights, pull requests merged in 2021-04, with the labels that each got.

#24 Change sample Docker compose file to work with NuoDB 4.2
  deploy/docker-compose.yaml
Labels: enhancement

#25 Give more time to YCSB container to start
  test/minikube/minikube_insights_test.go
Labels: meta

#26 Indicate that NuoDB Collector only supports InfluxDB 1.X
  README.md
  deploy/docker-compose.yaml
  deploy/monitor-stack.yaml
  test/docker/docker_insights_test.go
Labels: documentation, meta

#27 Add requirements doc
  README.md
Labels: documentation

#29 Corrected an issue on the "NuoDB Ops System Overview" databoard that resulted in the incorrect display of TE counts and aggregate TPS values in the Aggregate TPS panel.
  conf/provisioning/dashboards/nuodb/nuodb-ops-overview.json
Labels: bug
